# This workflow is usesd to test Composite Action using input/output

name: Testing Composite Action Input and Output test 

on:
  workflow_dispatch:

jobs:
  RunCompositeAction:
    name: Runs a Composite Action to test input and output variables
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Run the Composite Action that will print the input_var
        id: myCompositeAction
        uses: marcusmai-telia/actions-CompositeAction@main
        with:
          input_var: MyInputValue

      - name: Print out the output value from Composite Action
        run: echo "The output is = ${{ steps.myCompositeAction.outputs.output_var }}"
        shell: bash