name: Reusable workflow
on:
  workflow_call:
    inputs:
      input_var:
        type: string 
        description: "This is the input variable"
    outputs:
      output_var:
        description: "This is the output variable"
        value: ${{ steps.set-output-var.outputs.value }}
  workflow_dispatch:

jobs:
  PrintOutInputVariable:
    name: Runs a reusable Workflow to test input and output variables
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Print out the input_var
      run: echo "The input is = ${{ inputs.input_var }}"
      shell: bash
